### ISSUE TITLE
excel 导出 发现bug

### ISSUE THREAD

**Issue by Smecta** [xrkffgg/Kvue#12]
再测试 excel 导出的时候 发现 提示 export 报错 无法导出

尝试修改文件后 如图
![image](https://user-images.githubusercontent.com/30615458/112424892-2619a300-8d70-11eb-93d9-efb2b7a12693.png)

发现可以导出，但控制台会打印报错信息 如图
![image](https://user-images.githubusercontent.com/30615458/112424815-0a160180-8d70-11eb-9498-1fb0d5eb0887.png)

**Comment by xrkffgg** [comment]
我试下看看

**Comment by xrkffgg** [comment]
试一下 最新的，应该没报错了，有问题再说。

**Comment by Smecta** [comment]
> 试一下 最新的，应该没报错了，有问题再说。

刚测试了 没有问题了 👏
