### ISSUE TITLE
上传excel显示附件格式错误

### ISSUE THREAD

**Issue by lvchenjing** [xrkffgg/Kvue#3]
你好，我自你的demo界面上下载了demo.xlsx，然后再点击上传excel按钮，上传失败，提示我附件格式错误，这是什么原因，用你自己的demo.xlsx也格式错误？

**Comment by xrkffgg** [comment]
我这里未发现这个，请提供下详细的说明。

**Comment by xrkffgg** [comment]
@lvchenjing 抱歉，刚看到。
