### ISSUE TITLE
滚动表格BUG

### ISSUE THREAD

**Issue by jiubaK** [xrkffgg/Kvue#8]
滚动表格中，进行多次暂停/开始操作，展示的数据条数会变多。
`当然，这对于功能性展示来说，并不重要`

**Comment by xrkffgg** [comment]
感谢反馈，回头我看一下~

**Comment by xrkffgg** [comment]
由于动画延迟时间，暂停 / 开始，其实都包含了一个操作时间，我这里没处理。只是随便做的玩的。
